version: '1.0'
services:   
  mongo:    
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    volumes:
      - /data/mongo/db:/data/db
      - /data/mongo/conf:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    ports:
      - "27017:27017"
    restart: always
