// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Session struct {
	ID        string
	UserID    string
	Token     string
	CsrfToken string
	CreatedAt int64
	ExpiresAt int64
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    int64
	UpdatedAt    int64
}
