// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package repository

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (
    id,
    user_id,
    token,
    csrf_token,
    created_at,
    expires_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	Token     string
	CsrfToken string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM
    session
WHERE
    expires_at < ?1
`

func (q *Queries) DeleteSession(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, expiresAt)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :many
SELECT
    id, user_id, token, csrf_token, expires_at, last_used_at, created_at, updated_at
FROM
    session
WHERE
    token = ?1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionByToken, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.CsrfToken,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE
    session
SET
    expires_at = ?1,
    last_used_at = ?2,
    updated_at = ?3
WHERE
    id = ?4
`

type UpdateSessionParams struct {
	ExpiresAt  int64
	LastUsedAt sql.NullInt64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
