name: Demo Deploy

on:
  push:
    branches:
      - main

jobs:
  demo_deploy:
    name: Demo Deploy
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1

      - run: supabase link --project-ref $PROJECT_ID

      - run: supabase migration fetch --linked

      - run: supabase migration up --include-all --linked